helm:
  parameters:
  - name: app.image.repository
    value: 662930028566.dkr.ecr.us-east-1.amazonaws.com/ourrepo
    forcestring: true
  - name: app.image.tag
    value: latest
    forcestring: true
