{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.redis.name }}
    {{- include "nodeapp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
      - name: {{ .Values.redis.name }}
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.redis.service.targetPort }}
        resources:
          requests:
            cpu: {{ .Values.redis.resources.requests.cpu | quote }}
            memory: {{ .Values.redis.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.redis.resources.limits.cpu | quote }}
            memory: {{ .Values.redis.resources.limits.memory | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nodeapp.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.redis.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.targetPort }}
{{- end }}
