apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
data:
  DB_HOSTNAME: "mysql-service"        # Changed - use the actual service
  DB_PORT: "3306"                      # Changed - correct MySQL port
  REDIS_HOSTNAME: "redis-service"      # Correct
  REDIS_PORT: "6379"                   # Correct