# SecretStore - Connects to AWS Secrets Manager using Pod Identity
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system
---
# ExternalSecret for Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-external-secret
  namespace: default
spec:
  refreshInterval: 1h  # Sync from AWS every hour
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: mysql-secret  # Creates this Kubernetes secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
        DB_HOSTNAME: "{{ .host }}"
        DB_PORT: "{{ .port }}"
  data:
  - secretKey: username
    remoteRef:
      key: prod/db-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: prod/db-credentials
      property: password
  - secretKey: host
    remoteRef:
      key: prod/db-credentials
      property: host
  - secretKey: port
    remoteRef:
      key: prod/db-credentials
      property: port
---
# ExternalSecret for Redis Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REDIS_HOSTNAME: "{{ .host }}"
        REDIS_PORT: "{{ .port }}"
  data:
  - secretKey: host
    remoteRef:
      key: prod/redis-credentials
      property: host
  - secretKey: port
    remoteRef:
      key: prod/redis-credentials
      property: port